### ISSUE TITLE
[Bug]: 0.6.11. Virtual Input does not show up in HA

### ISSUE THREAD

**Issue by rolandpj** [JoDehli/PyLoxone#293]
### Describe the bug

After the upgrade from 0.6.10 to 0.6.11 the Virtual Input entity does not show up in HA.

In Loxone I use a Virtual Input which is configured as "Digital Input" in Loxone. Until the latest release this Virtual Input showed up as Push Button in HA. With 0.6.11. this entity disappeared

### Firmware of your Miniserver

Gen1 15.0.5.29

### HomeAssistant install method

Hassio

### Version of HomeAssistant

2024.7.4

### Version of Pyloxone

0.6.11

### Update pyloxone

yes

### Log

Settings for the log can be found on the main page under the section Log Configuration

**Comment by JoDehli** [comment]
@gigatexel it has something to do with the latest changes we made. Can you have a look?

**Comment by gigatexel** [comment]
Can you post a detailed screenshot of your Loxone config for this VI? I can that reproduce & fix.

**Comment by rolandpj** [comment]
sure:
![image](https://github.com/user-attachments/assets/0b4a38a7-900f-41ac-b780-e57eed54622e)
![image](https://github.com/user-attachments/assets/5ecf0513-34b8-41e3-87d3-4a1a739537fa)

**Comment by gigatexel** [comment]
You have configured it as a pushbutton, not a Digital input.
These now appear as a button in Home Assistant, which is more correct than
a switch.

Op di 6 aug 2024 om 07:17 schreef rolandpj ***@***.***>

**Comment by gigatexel** [comment]
Can you replace the code in custom_components/loxone/button.py with this code: https://github.com/gigatexel/PyLoxone/blob/gigatexel-patch-button/custom_components/loxone/button.py

**Comment by rolandpj** [comment]
ok.. i didn't know that that has been changed. 
It shows up as button now in HA with 0.6.11.

> Can you replace the code in custom_components/loxone/button.py with this code: https://github.com/gigatexel/PyLoxone/blob/gigatexel-patch-button/custom_components/loxone/button.py

I also replace the button.py with this code.. but there is no difference to 06.11. What should happen with the new button.py?

**Comment by gigatexel** [comment]
Should fix the button not responding

Op di 6 aug 2024 om 16:43 schreef rolandpj ***@***.***>

**Comment by rolandpj** [comment]
ok.. no, it doesnt work. I replace the code and restarted HA:
![image](https://github.com/user-attachments/assets/c26c4ac4-30e0-4fb7-a614-fdf65102227d)

**Comment by JoDehli** [comment]
@rolandpj try the newest version I released a few minutes ago

**Comment by rolandpj** [comment]
Still the Same, old entity ist not Provided.

**Comment by JoDehli** [comment]
@rolandpj what does it mean when you say the old entities. Do you have a new entity instead?

**Comment by rolandpj** [comment]
With PyLoxone 0.6.10 my entities showed up as switch:
![image](https://github.com/user-attachments/assets/465348f2-408a-4fc5-b0f4-a34a3bbf06b0)

Starting with 06.11 they show up as button:
![image](https://github.com/user-attachments/assets/7d274960-1ad4-488c-9e43-f644dbc88379)

With "the old entitiy" i mean the first switch entity, this still shows up as orphaned. 

Is this the expected behaviour?

**Comment by gigatexel** [comment]
> With PyLoxone 0.6.10 my entities showed up as switch: ![image](https://private-user-images.githubusercontent.com/26387147/355688334-465348f2-408a-4fc5-b0f4-a34a3bbf06b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTQ1MDQsIm5iZiI6MTcyMzAxNDIwNCwicGF0aCI6Ii8yNjM4NzE0Ny8zNTU2ODgzMzQtNDY1MzQ4ZjItNDA4YS00ZmM1LWIwZjQtYTM0YTNiYmYwNmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA3MDMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNTNiZGEwNGNmN2QxNTg0MjdjZjI1OTNjODQ2MjY4MjVjNGMxODU1ZjUxYTQxNjU2NjM1ZWU4NjQ5YzkyOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WdVd7JohE0xwRJLxACWQeD4MW6tjBh54k212GUNMA-A)
> 
> Starting with 06.11 they show up as button: ![image](https://private-user-images.githubusercontent.com/26387147/355688400-7d274960-1ad4-488c-9e43-f644dbc88379.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTQ1MDQsIm5iZiI6MTcyMzAxNDIwNCwicGF0aCI6Ii8yNjM4NzE0Ny8zNTU2ODg0MDAtN2QyNzQ5NjAtMWFkNC00ODhjLTllNDMtZjY0NGRiYzg4Mzc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA3MDMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NjI4NDY0NjIzYmIzMWMyOTk5YTYxMWM0NjJjYjc2YzUwNjcwM2QxOTAwNzUzYjE5NjA5M2I3YjFjNjkxYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wCtXr0xnNhRZQ0Ov922oWt_XN-oQ7TfZtOxNobaa5mw)
> 
> With "the old entitiy" i mean the first switch entity, this still shows up as orphaned.
> 
> Is this the expected behaviour?

Yes, this is expected. I have not programmed the automatic deletion of the "old" switch entities.
You can safely remove the unused entities and now use the buttons.

**Comment by JoDehli** [comment]
@rolandpj 
@gigatexel 

Of course this is expected as it becomes a different platform. The old "switches" are now called "buttons". 
The reason was that in the past home assistant had not button implementation. So please manually delete the old entities and change it anywhere if you used them in automations and scripts.

**Comment by rolandpj** [comment]
ok thanks for clarification.. then I will go on with reconfiguration in my automations.
BTW, Amazon Alexa did not recognize the button...will go on with a workaround..
