### ISSUE TITLE
TextStates problem

### ISSUE THREAD

**Issue by Petahh** [JoDehli/PyLoxone#86]
Hello guys, any idea how to fix this history graph to text based. This was OK in previous version of HASS. I can't figure out what am I doing wrong... thanks a lot for any suggestion.

![Screen Shot 2021-09-17 at 7 42 29 PM](https://user-images.githubusercontent.com/7292374/133831589-87dcf651-fc59-4384-bca7-0cf2b9ca3daa.png)
![Screen Shot 2021-09-17 at 7 42 36 PM](https://user-images.githubusercontent.com/7292374/133831593-80aa0574-1213-423c-bb68-a78e4b245fd5.png)
.
![Screen Shot 2021-09-17 at 7 42 56 PM](https://user-images.githubusercontent.com/7292374/133831602-98a91c15-f0f7-4761-b231-ffb2c3bee98d.png)

**Comment by JoDehli** [comment]
What values are shown in HA in the developer section for the sensor? Did it change with a new HA Version or did it never showed right?

**Comment by Petahh** [comment]
> What values are shown in HA in the developer section for the sensor? Did it change with a new HA Version or did it never showed right?

`uuid: 172c222d-033c-edfc-ffff08bdc1be5cb2
plattform: loxone
show_last_changed: 'true'
unit_of_measurement: ''
friendly_name: AC unit
icon: hass:fan`

It was fine on version 2021.5.4 of HASS.

**Comment by JoDehli** [comment]
I meant what state does it show? Does it shows the same value as in the loxone? 

If it is only on sensor you can make a template sensor of this sensor and use the templated version.

**Comment by Petahh** [comment]
> I meant what state does it show? Does it shows the same value as in the loxone?
> 
> If it is only on sensor you can make a template sensor of this sensor and use the templated version.

State is fine, it shows "Off" as its supposed to.
How can I template it? I was also trying to customize it but no success. 
I can't get rid of homeassistant thinking this sensor has unit...

**Comment by JoDehli** [comment]
What original device or sensor is it in loxone. Maybe I can make a test on the weekend.

**Comment by JoDehli** [comment]
If you want you can try the newest version for Pyloxone. I have not made a release or tag so you  must download the source of the main branch and copy it to your home assistant custom component folder.

**Comment by Petahh** [comment]
I have managed to resolve it by template:

`template: `
`  - sensor:`
 `   - name: AC unit`
     ` state: "{{ states('sensor.ac_unit_loxone’) }}"`

Not sure why I had the problem.. it might be due to upgrade of HASS, maybe something got screwed up

**Comment by JoDehli** [comment]
@Petahh They changed something on the unit on the version. I already implemented in the newest version on git. Would be interesting if it works with the newest version. Maybe I release a new version this weekend. Then you can update it over hacs. 

What kind of device is the AC unit in loxone. Maybe I can implement the complete device type to ha.

**Comment by Petahh** [comment]
> @Petahh They changed something on the unit on the version. I already implemented in the newest version on git. Would be interesting if it works with the newest version. Maybe I release a new version this weekend. Then you can update it over hacs.
> 
> What kind of device is the AC unit in loxone. Maybe I can implement the complete device type to ha.

It’s a type ‘TextState’ I have posted snip from loxone json in the first post.

**Comment by JoDehli** [comment]
@Petahh You can try the newest version 0.3.8. It is marked as beta for now. Maybe it solves your problem.

**Comment by JoDehli** [comment]
@Petahh I added a option for your problem in the newest 0.3.8. 
You can force a text output by adding the unit_of_measurement like so:


```yaml
sensor:
  - platform: loxone
    name: Motion Sensor Info Text
    uuidAction: "17d4b2a6-021c-9ff0-ffff5a3f44c96e13"
    unit_of_measurement: "None"
```

You can use "None", "none" or "-" for the unit_of_measurement.

Can you report if it worked for you

**Comment by Petahh** [comment]
> @Petahh I added a option for your problem in the newest 0.3.8.
> You can force a text output by adding the unit_of_measurement like so:
> 
> ```yaml
> sensor:
>   - platform: loxone
>     name: Motion Sensor Info Text
>     uuidAction: "17d4b2a6-021c-9ff0-ffff5a3f44c96e13"
>     unit_of_measurement: "None"
> ```
> 
> You can use "None", "none" or "-" for the unit_of_measurement.
> 
> Can you report if it worked for you

Hello, unfortunately no change. 
Still facing same issue on the untemplated sensors.

**Comment by JoDehli** [comment]
@Petahh have you used the newest beta release? You have to reinstall it to get the latest version.

**Comment by Petahh** [comment]
> @Petahh have you used the newest beta release? You have to reinstall it to get the latest version.

Yes, I have replaced entire loxone folder in custom_components with latest beta version you published. It might be something screwed up with my hass. Don’t spend more time on this, I managed to get it corrected with templates.
